config/routes.rb
Rails.application.routes.draw do
  resources :report_ramadhans, :except => [:edit, :update, :delete]
  resources :majors
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :students, controllers: { sessions: 'students/sessions', registrations: 'students/registrations' }
  devise_scope :student do
    get 'sign_in', to: 'students/sessions#new'
    get '/students/sign_out' => 'students/sessions#destroy'
  end
  resources :homes
  get "/homes/myreports" => "/homes/myreports"
  get "/homes/profile" => "/homes/profile"
  get "/profile/index" => "/profile/index"
  root to: 'homes#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/grade.rb
class Grade < ApplicationRecord
end

app/models/major.rb
class Major < ApplicationRecord
  has_many :students
  has_many :report_ramadhans
end

app/models/report_ramadhan.rb
class ReportRamadhan < ApplicationRecord
  belongs_to :major
  belongs_to :student
  has_many_attached :files

  paginates_per 7

  # validates :puasa ,:tadarus, :tarawih, :subuh, :dzuhur,:ashar ,:magrib,
  #             :isya, presence: true
  validates :puasa ,:tadarus, :tarawih, :subuh, :dzuhur,:ashar ,:magrib,
                         :isya, :tanggal, :files, presence: true

  validates :files, presence: true, blob: { content_type: :image }

end

app/models/student.rb
class Student < ApplicationRecord
  has_one_attached :avatar
  belongs_to :major
  has_many :report_ramadhans, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/grades_controller.rb
class GradesController < InheritedResources::Base

  private

    def grade_params
      params.require(:grade).permit(:class)
    end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :authenticate_student!

  def index
    @report_ramadhan = current_student.report_ramadhans.new
  end

  def myreports
    @report_ramadhans = current_student.report_ramadhans.all
  end

  def show
    @report_ramadhans = current_student.report_ramadhans.all.order(tanggal: :desc ).page params[:page]
  end

  def profile

  end

end

app/controllers/majors_controller.rb
class MajorsController < InheritedResources::Base

  private

    def major_params
      params.require(:major).permit(:name)
    end

end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  before_action :authenticate_student!
  def index

  end
end

app/controllers/report_ramadhans_controller.rb
class ReportRamadhansController < ApplicationController
  require 'twilio-ruby'

  before_action :authenticate_student!
  before_action :set_report, only: [:show, :edit, :update]

  # def index
  #   @report_ramadhans = current_student.report_ramadhans.all
  #   # .order(created_at: :desc).page params[:page]
  # end

  def new
    @report_ramadhan = current_student.report_ramadhans.new
  end

  def create
    @report_ramadhan = current_student.report_ramadhans.new(report_ramadhan_params)
      if @report_ramadhan.save
        begin
          send_message_to_afza
        rescue
          false
        end
      end
      if @report_ramadhan.save
        begin
          send_message_to_admin
        rescue
          false
        end
      end
    respond_to do |format|
      if @report_ramadhan.save
        format.html { redirect_to homes_path, notice: 'Laporan Agenda Ramadhan berhasil dibuat.' }
        format.json { render :show, status: :created }
      else
        format.html { redirect_to homes_path, notice: 'Laporan Agenda Ramadhan gagal dibuat harap isi kolom Bukti Laporan .' }
        format.json { render json: @report_ramadhan.errors, status: :unprocessable_entity }
      end
    end
  end

  private

    def report_ramadhan_params
      params.require(:report_ramadhan).permit(:puasa, :tadarus, :tarawih, :subuh, :dzuhur,
                                         :ashar, :magrib, :isya, :duha, :tahajud, :taubat,
                                        :hajat, :alasan, :student_id, :major_id, :tanggal, files: [])
    end

    def set_report_ramadhan_params
      @report = ReportRamadhan.find(params[:id])
    end

    def send_message_to_afza
      account_sid = 'AC933b0a4024b523adcba2457b758dbdc4'
      auth_token = 'd34fdbfe23f1855e76ca994fdb1b113c'
      client = Twilio::REST::Client.new(account_sid, auth_token)

      from = '+16623378759'
      to = '+6282127015766'

      client.messages.create(
      from: from,
      to: to,
      body: "Assalamualaikum.....,#{@report_ramadhan.student.firstname.to_s} #{@report_ramadhan.student.lastname.to_s} kelas #{@report_ramadhan.major.name} baru saja mengirimkan laporan untuk tanggal #{@report_ramadhan.tanggal}!"
      )
    end

    def send_message_to_admin
      account_sid = 'AC8a60fb745765bb9b6e65778abf5e0800'
      auth_token = '426f01bdc59dc636b0864422b645a5aa'
      client = Twilio::REST::Client.new(account_sid, auth_token)

      from = '+18482259794'
      to = '+6281224864547'

      client.messages.create(
      from: from,
      to: to,
      body: "Assalamualaikum.....,#{@report_ramadhan.student.firstname.to_s} #{@report_ramadhan.student.lastname.to_s} kelas #{@report_ramadhan.major.name} baru saja mengirimkan laporan untuk tanggal #{@report_ramadhan.tanggal}!"
      )
    end

end

app/controllers/stages_controller.rb
class StagesController < InheritedResources::Base

  private

    def stage_params
      params.require(:stage).permit(:grade)
    end

end

app/controllers/students/passwords_controller.rb
# frozen_string_literal: true

class Students::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/students/sessions_controller.rb
# frozen_string_literal: true

class Students::SessionsController < Devise::SessionsController
  layout "signup"
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/students/unlocks_controller.rb
# frozen_string_literal: true

class Students::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/majors_helper.rb
module MajorsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/report_ramadhans_helper.rb
module ReportRamadhansHelper
end

app/helpers/stages_helper.rb
module StagesHelper
end

app/views/grades/_form.html.erb
<%= form_with(model: grade, local: true) do |form| %>
  <% if grade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(grade.errors.count, "error") %> prohibited this grade from being saved:</h2>

      <ul>
        <% grade.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :class %>
    <%= form.text_field :class %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/grades/edit.html.erb
<h1>Editing Grade</h1>

<%= render 'form', grade: @grade %>

<%= link_to 'Show', @grade %> |
<%= link_to 'Back', grades_path %>

app/views/grades/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Grades</h1>

<table>
  <thead>
    <tr>
      <th>Class</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @grades.each do |grade| %>
      <tr>
        <td><%= grade.class %></td>
        <td><%= link_to 'Show', grade %></td>
        <td><%= link_to 'Edit', edit_grade_path(grade) %></td>
        <td><%= link_to 'Destroy', grade, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Grade', new_grade_path %>

app/views/grades/new.html.erb
<h1>New Grade</h1>

<%= render 'form', grade: @grade %>

<%= link_to 'Back', grades_path %>

app/views/grades/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Class:</strong>
  <%= @grade.class %>
</p>

<%= link_to 'Edit', edit_grade_path(@grade) %> |
<%= link_to 'Back', grades_path %>

app/views/majors/_form.html.erb
<%= form_with(model: major, local: true) do |form| %>
  <% if major.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(major.errors.count, "error") %> prohibited this major from being saved:</h2>

      <ul>
        <% major.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/majors/edit.html.erb
<h1>Editing Major</h1>

<%= render 'form', major: @major %>

<%= link_to 'Show', @major %> |
<%= link_to 'Back', majors_path %>

app/views/majors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Majors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @majors.each do |major| %>
      <tr>
        <td><%= major.name %></td>
        <td><%= link_to 'Show', major %></td>
        <td><%= link_to 'Edit', edit_major_path(major) %></td>
        <td><%= link_to 'Destroy', major, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Major', new_major_path %>

app/views/majors/new.html.erb
<h1>New Major</h1>

<%= render 'form', major: @major %>

<%= link_to 'Back', majors_path %>

app/views/majors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @major.name %>
</p>

<%= link_to 'Edit', edit_major_path(@major) %> |
<%= link_to 'Back', majors_path %>

app/views/report_ramadhans/_form.html.erb
<div class="container">
  <h2>Laporan Amalan di bulan Ramadhan</h2>
  <%= form_for @report_ramadhan do |form| %>
    <div class="row">
      <div class="col-25">
        <%= form.label :tanggal %>
      </div>
      <div class="col-75">
        <%= form.date_field :tanggal, data:{ provide:'datepicker' } %>

      </div>
    </div>

    <div class="row">
      <div class="col-25">
        <%= form.label :puasa %>
      </div>
      <div class="col-75">
        <%= form.select :puasa, options_for_select([['Puasa', "Puasa"], ['Tidak',"Tidak"]], selected: @report_ramadhan.puasa), required: true  %>

      </div>
    </div>

    <div class="row">
      <div class="col-25">
        <%= form.label :tadarus %>
      </div>
      <div class="col-75">
        <%= form.text_field :tadarus, placeholder: "Misal: Yasin(1)-(20)", required: true %>
      </div>
    </div>

    <div class="row" hidden="">
      <div class="col-75">
        <%= form.text_field :major_id, :value => current_student.major_id, required: true %>
      </div>
    </div>

    <div class="row">
      <div class="col-25">
        <%= form.label :tarawih %>
      </div>
      <div class="col-75">
        <%= form.select :tarawih, options_for_select([['tarawih', "tarawih"], ['Tidak',"Tidak"]], selected: @report_ramadhan.tarawih), required: true  %>
      </div>
    </div>

    <div class="row">
      <div class="col-25">
        <%= form.label :subuh %>
      </div>
      <div class="col-75">
        <%= form.text_field :subuh, placeholder: "Misal: 05:03", required: true%>
      </div>
    </div>

    <div class="row">
      <div class="col-25">
        <%= form.label :dzuhur %>
      </div>
      <div class="col-75">
        <%= form.text_field :dzuhur, placeholder: "Misal: 12:13", required: true  %>
      </div>
    </div>

    <div class="row">
      <div class="col-25">
        <%= form.label :ashar %>
      </div>
      <div class="col-75">
        <%= form.text_field :ashar, placeholder: "Misal: 15:23" %>
      </div>
    </div>

    <div class="row">
      <div class="col-25">
        <%= form.label :magrib %>
      </div>
      <div class="col-75">
        <%= form.text_field :magrib, placeholder: "Misal: 18:07" %>
      </div>
    </div>

    <div class="row">
      <div class="col-25">
        <%= form.label :isya %>
      </div>
      <div class="col-75">
        <%= form.text_field :isya, placeholder: "Misal: 19:23" %>
      </div>
    </div>

    <div class="row">
      <div class="col-25">
        <%= form.label :duha %>
      </div>
      <div class="col-75">
        <%= form.text_field :duha, placeholder: "Misal: 10:56" %>
      </div>
    </div>

    <div class="row">
      <div class="col-25">
        <%= form.label :tahajud %>
      </div>
      <div class="col-75">
        <%= form.text_field :tahajud, placeholder: "Misal: 02:30" %>
      </div>
    </div>

    <div class="row">
      <div class="col-25">
        <%= form.label :taubat %>
      </div>
      <div class="col-75">
        <%= form.text_field :taubat, placeholder: "Misal: 22:42" %>
      </div>
    </div>

    <div class="row">
      <div class="col-25">
        <%= form.label :hajat %>
      </div>
      <div class="col-75">
        <%= form.text_field :hajat, placeholder: "Misal: 10:03" %>
      </div>
    </div>

    <div class="row">
      <div class="col-25">
        <%= form.label :bukti_laporan_hasil_collapse %>
      </div>
      <div class="col-75">
        <%= form.file_field :files, multiple: true, placeholder: "aaa" %>
      </div>
    </div>

    <div class="row">
      <div class="col-25">
        <%= form.label :alasan %>
      </div>
      <div class="col-75">
        <%= form.text_area(:alasan, size: '50x10') %>
      </div>
    </div>

    <div class="row" hidden="">
      <div class="col-25">
        <%= form.label :student_id %>
      </div>
      <div class="col-75">
        <%= form.text_field :student_id %>
      </div>
    </div>

    <div class="row">
      <%= form.submit "Kirim Laporan", :class => "kirim btn btn-primary", id: "kirim" %>
    </div>
  <% end %>
</div>
</div>

app/views/report_ramadhans/edit.html.erb
<h1>Editing Report Ramadhan</h1>

<%= render 'form', report_ramadhan: @report_ramadhan %>

<%= link_to 'Show', @report_ramadhan %> |
<%= link_to 'Back', report_ramadhans_path %>

app/views/report_ramadhans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Report Ramadhans</h1>

<table>
  <thead>
    <tr>
      <th>Puasa</th>
      <th>Tadarus</th>
      <th>Tarawih</th>
      <th>Subuh</th>
      <th>Dzuhur</th>
      <th>Ashar</th>
      <th>Magrib</th>
      <th>Isya</th>
      <th>Duha</th>
      <th>Tahajud</th>
      <th>Taubat</th>
      <th>Hajat</th>
      <th>Alasan</th>
      <th>Student</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @report_ramadhans.each do |report_ramadhan| %>
      <tr>
        <td><%= report_ramadhan.puasa %></td>
        <td><%= report_ramadhan.tadarus %></td>
        <td><%= report_ramadhan.tarawih %></td>
        <td><%= report_ramadhan.subuh %></td>
        <td><%= report_ramadhan.dzuhur %></td>
        <td><%= report_ramadhan.ashar %></td>
        <td><%= report_ramadhan.magrib %></td>
        <td><%= report_ramadhan.isya %></td>
        <td><%= report_ramadhan.duha %></td>
        <td><%= report_ramadhan.tahajud %></td>
        <td><%= report_ramadhan.taubat %></td>
        <td><%= report_ramadhan.hajat %></td>
        <td><%= report_ramadhan.alasan %></td>
        <td><%= report_ramadhan.student_id %></td>
        <td><%= link_to 'Show', report_ramadhan %></td>
        <td><%= link_to 'Edit', edit_report_ramadhan_path(report_ramadhan) %></td>
        <td><%= link_to 'Destroy', report_ramadhan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Report Ramadhan', new_report_ramadhan_path %>

app/views/report_ramadhans/new.html.erb
<h1>New Report Ramadhan</h1>

<%= render 'form', report_ramadhan: @report_ramadhan %>

<%= link_to 'Back', report_ramadhans_path %>

app/views/report_ramadhans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Puasa:</strong>
  <%= @report_ramadhan.puasa %>
</p>

<p>
  <strong>Tadarus:</strong>
  <%= @report_ramadhan.tadarus %>
</p>

<p>
  <strong>Tarawih:</strong>
  <%= @report_ramadhan.tarawih %>
</p>

<p>
  <strong>Subuh:</strong>
  <%= @report_ramadhan.subuh %>
</p>

<p>
  <strong>Dzuhur:</strong>
  <%= @report_ramadhan.dzuhur %>
</p>

<p>
  <strong>Ashar:</strong>
  <%= @report_ramadhan.ashar %>
</p>

<p>
  <strong>Magrib:</strong>
  <%= @report_ramadhan.magrib %>
</p>

<p>
  <strong>Isya:</strong>
  <%= @report_ramadhan.isya %>
</p>

<p>
  <strong>Duha:</strong>
  <%= @report_ramadhan.duha %>
</p>

<p>
  <strong>Tahajud:</strong>
  <%= @report_ramadhan.tahajud %>
</p>

<p>
  <strong>Taubat:</strong>
  <%= @report_ramadhan.taubat %>
</p>

<p>
  <strong>Hajat:</strong>
  <%= @report_ramadhan.hajat %>
</p>

<p>
  <strong>Alasan:</strong>
  <%= @report_ramadhan.alasan %>
</p>

<p>
  <strong>Student:</strong>
  <%= @report_ramadhan.student_id %>
</p>

<%= link_to 'Edit', edit_report_ramadhan_path(@report_ramadhan) %> |
<%= link_to 'Back', report_ramadhans_path %>