config/routes.rb
Rails.application.routes.draw do
  resources :report_ramadhans, :except => [:edit, :update, :delete]
  resources :majors
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :students, controllers: { sessions: 'students/sessions', registrations: 'students/registrations' }
  devise_scope :student do
    get 'sign_in', to: 'students/sessions#new'
    get '/students/sign_out' => 'students/sessions#destroy'
  end
  resources :homes
  get "/homes/myreports" => "/homes/myreports"
  get "/homes/profile" => "/homes/profile"
  get "/profile/index" => "/profile/index"
  root to: 'homes#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/grade.rb
class Grade < ApplicationRecord
end

app/models/major.rb
class Major < ApplicationRecord
  has_many :students
  has_many :report_ramadhans
end

app/models/report_ramadhan.rb
class ReportRamadhan < ApplicationRecord
  belongs_to :major
  belongs_to :student
  has_many_attached :files

  paginates_per 7

  # validates :puasa ,:tadarus, :tarawih, :subuh, :dzuhur,:ashar ,:magrib,
  #             :isya, presence: true
  validates :puasa ,:tadarus, :tarawih, :subuh, :dzuhur,:ashar ,:magrib,
                         :isya, :tanggal, :files, presence: true

  validates :files, presence: true, blob: { content_type: :image }

end

app/models/student.rb
class Student < ApplicationRecord
  has_one_attached :avatar
  belongs_to :major
  has_many :report_ramadhans, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/grades_controller.rb
class GradesController < InheritedResources::Base

  private

    def grade_params
      params.require(:grade).permit(:class)
    end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :authenticate_student!

  def index
    @report_ramadhan = current_student.report_ramadhans.new
  end

  def myreports
    @report_ramadhans = current_student.report_ramadhans.all
  end

  def show
    @report_ramadhans = current_student.report_ramadhans.all.order(tanggal: :desc ).page params[:page]
  end

  def profile

  end

end

app/controllers/majors_controller.rb
class MajorsController < InheritedResources::Base

  private

    def major_params
      params.require(:major).permit(:name)
    end

end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  before_action :authenticate_student!
  def index

  end
end

app/controllers/report_ramadhans_controller.rb
class ReportRamadhansController < ApplicationController
  require 'twilio-ruby'

  before_action :authenticate_student!
  before_action :set_report, only: [:show, :edit, :update]

  # def index
  #   @report_ramadhans = current_student.report_ramadhans.all
  #   # .order(created_at: :desc).page params[:page]
  # end

  def new
    @report_ramadhan = current_student.report_ramadhans.new
  end

  def create
    @report_ramadhan = current_student.report_ramadhans.new(report_ramadhan_params)
      if @report_ramadhan.save
        begin
          send_message_to_afza
        rescue
          false
        end
      end
      if @report_ramadhan.save
        begin
          send_message_to_admin
        rescue
          false
        end
      end
    respond_to do |format|
      if @report_ramadhan.save
        format.html { redirect_to homes_path, notice: 'Laporan Agenda Ramadhan berhasil dibuat.' }
        format.json { render :show, status: :created }
      else
        format.html { redirect_to homes_path, notice: 'Laporan Agenda Ramadhan gagal dibuat harap isi kolom Bukti Laporan .' }
        format.json { render json: @report_ramadhan.errors, status: :unprocessable_entity }
      end
    end
  end

  private

    def report_ramadhan_params
      params.require(:report_ramadhan).permit(:puasa, :tadarus, :tarawih, :subuh, :dzuhur,
                                         :ashar, :magrib, :isya, :duha, :tahajud, :taubat,
                                        :hajat, :alasan, :student_id, :major_id, :tanggal, files: [])
    end

    def set_report_ramadhan_params
      @report = ReportRamadhan.find(params[:id])
    end

    def send_message_to_afza
      account_sid = 'AC933b0a4024b523adcba2457b758dbdc4'
      auth_token = 'd34fdbfe23f1855e76ca994fdb1b113c'
      client = Twilio::REST::Client.new(account_sid, auth_token)

      from = '+16623378759'
      to = '+6282127015766'

      client.messages.create(
      from: from,
      to: to,
      body: "Assalamualaikum.....,#{@report_ramadhan.student.firstname.to_s} #{@report_ramadhan.student.lastname.to_s} kelas #{@report_ramadhan.major.name} baru saja mengirimkan laporan untuk tanggal #{@report_ramadhan.tanggal}!"
      )
    end

    def send_message_to_admin
      account_sid = 'AC8a60fb745765bb9b6e65778abf5e0800'
      auth_token = '426f01bdc59dc636b0864422b645a5aa'
      client = Twilio::REST::Client.new(account_sid, auth_token)

      from = '+18482259794'
      to = '+6281224864547'

      client.messages.create(
      from: from,
      to: to,
      body: "Assalamualaikum.....,#{@report_ramadhan.student.firstname.to_s} #{@report_ramadhan.student.lastname.to_s} kelas #{@report_ramadhan.major.name} baru saja mengirimkan laporan untuk tanggal #{@report_ramadhan.tanggal}!"
      )
    end

end

app/controllers/stages_controller.rb
class StagesController < InheritedResources::Base

  private

    def stage_params
      params.require(:stage).permit(:grade)
    end

end

app/controllers/students/sessions_controller.rb
# frozen_string_literal: true

class Students::SessionsController < Devise::SessionsController
  layout "signup"
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/students/unlocks_controller.rb
# frozen_string_literal: true

class Students::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/majors_helper.rb
module MajorsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/report_ramadhans_helper.rb
module ReportRamadhansHelper
end

app/helpers/stages_helper.rb
module StagesHelper
end

app/views/homes/index.html.erb
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
<style>
  .navbar {
    /*position: fixed;*/
  }
</style>
<nav class="navbar navbar-expand-md bg-dark navbar-dark" id="navbar">
  <a class="navbar-brand hello" id="hello" >
    <% if current_student.avatar.attached? %>
      <%= image_tag url_for(current_student.avatar), class:"image-avatar", id: "avat" %>
    <% else %>
      <img src="<%= asset_path('avatar.jpg')%>" alt="avatar" id="avat" class="image-avatar">
    <% end %>
    <%= current_student.firstname %>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="collapsibleNavbar">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to "Dashboard", homes_path , :class => 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "Laporanku", homes_myreports_path, :class => 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "Profil", profile_index_path, :class => 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "Logout", destroy_student_session_path, method: :delete, :class => 'nav-link logout', :id => "logout"   %>
      </li>
    </ul>
  </div>
</nav>
<!-- <div class="container">
  <div class="row">
    <h2 class="ban">Data Informasi Corona Indonesia</h2>
    <div class="col-sm" id="konfirmasi">
      <%= fa_icon "plus 2x", class: "plus" %>Total Kasus
    </div>
    <div class="col-sm" id="sembuh">
      <%= fa_icon "heart 2x", class: "heart" %> Sembuh
    </div>
    <div class="col-sm" id="meninggal">
      <%= fa_icon "frown-o 2x", class: "frown-o" %> Meninggal
    </div>
  </div>
</div> -->

<div class="container banner-corona">
    <center>
      <h3 class="caption-banner">Data Informasi Corona </h3><em>(klik)</em>
      <hr>
    </center>
  <div class="row" id="data-cor">
    <div class="col" id="konfirmasi" style="border-right: 1px solid black;">
      <%= fa_icon "plus 2x", class: "plus" %><br/ >
      Total Kasus
    </div>
    <div class="col order-12" id="meninggal" style="border-left: 1px solid black;">
      <%= fa_icon "frown-o 2x", class: "frown-o" %><br />
      Meninggal<br />
    </div>
    <div class="col order-1" id="sembuh">
      <%= fa_icon "heart 2x", class: "heart" %><br />
      Sembuh
    </div>
  </div>
</div>
<!-- <button id="konfirmasi"></button>
<button id="sembuh"></button>
<button id="meninggal"></button> -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<!-- <script>
$.ajax({
        url: "https://api.kawalcorona.com/indonesia",
        type: 'GET',
        dataType: 'json', // added data type
        success: function(res) {
            console.log(res);
            alert(res);
        }
    });
</script> -->
<script>
$(document).ready(function(){
var stream = 'https://www.trackcorona.live/api/countries/id';
    $.ajax({
        url: stream,
        dataType: "json",
        contentType: 'application/json',
        success: function(respone, status) {
            var konfirmasi = $('#konfirmasi');
            var sembuh = $('#sembuh');
            var meninggal = $('#meninggal');
              // list.empty();
              $(respone.data).each(function (index, element) {
                  konfirmasi.append(element.confirmed);
                  // list.append('<li>'+element.dead+'<li>')
              })
              $(respone.data).each(function (index, element) {
                  sembuh.append(element.recovered);
                  // list.append('<li>'+element.dead+'<li>')
              })

              $(respone.data).each(function (index, element) {
                  meninggal.append(element.dead);
                  // list.append('<li>'+element.dead+'<li>')
              })
        }
    });
});
</script>
<br>
<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, class: "alert alert-info", id: "alerts" %>
<% end %>

<%= render partial: '/report_ramadhans/form' %>

  <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal" hidden="">Open Modal</button>

  <!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content spinner-border text-primary">
        <!-- ICON -->
      </div>

    </div>
  </div>

<script>
  $('document').ready(function () {
    setTimeout(function () {
      $('.alert-info').slideUp();
    }, 2000);
  });
</script>


<script>
$(document).ready(function(){
  $(".kirim").click(function(){
    $(".btn-info").click();
  });
});
</script>

<script>
$(document).ready(function(){
  $(".caption-banner").click(function(){
    $("#data-cor").slideToggle("slow");
  });
});
</script>

app/views/homes/myreports.html.erb
<style>
table {
  border-collapse: collapse;
  border-spacing: 0;
  width: 100%;
  border: 1px solid #ddd;
}

th, td {
  text-align: left;
  padding: 8px;
}

tr:nth-child(even){background-color: #f2f2f2}
</style>

<h2>Responsive Table</h2>
<p>If you have a table that is too wide, you can add a container element with overflow-x:auto around the table, and it will display a horizontal scroll bar when needed.</p>
<p>Resize the browser window to see the effect. Try to remove the div element and see what happens to the table.</p>

<div style="overflow-x:auto;">
  <table>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Points</th>
      <th>Points</th>
      <th>Points</th>
      <th>Points</th>
      <th>Points</th>
      <th>Points</th>
      <th>Points</th>
      <th>Points</th>
      <th>Points</th>
      <th>Points</th>
    </tr>
    <tr>
      <td>Jill</td>
      <td>Smith</td>
      <td>50</td>
      <td>50</td>
      <td>50</td>
      <td>50</td>
      <td>50</td>
      <td>50</td>
      <td>50</td>
      <td>50</td>
      <td>50</td>
      <td>50</td>
    </tr>
    <tr>
      <td>Eve</td>
      <td>Jackson</td>
      <td>94</td>
      <td>94</td>
      <td>94</td>
      <td>94</td>
      <td>94</td>
      <td>94</td>
      <td>94</td>
      <td>94</td>
      <td>94</td>
      <td>94</td>
    </tr>
    <tr>
      <td>Adam</td>
      <td>Johnson</td>
      <td>67</td>
      <td>67</td>
      <td>67</td>
      <td>67</td>
      <td>67</td>
      <td>67</td>
      <td>67</td>
      <td>67</td>
      <td>67</td>
      <td>67</td>
    </tr>
  </table>
</div>

app/views/homes/show.html.erb
<style>
table {
  border-collapse: collapse;
  border-spacing: 0;
  width: 100%;
  border: 1px solid #ddd;
}

th {
  text-align: left;
  padding: 12px;
}
td {
  text-align: left;
  padding: 8px;
}

tr:nth-child(even){background-color: #f2f2f2}
</style>

<nav class="navbar navbar-expand-md bg-dark navbar-dark" id="navbar">
  <a class="navbar-brand hello" id="hello" >
    <% if current_student.avatar.attached? %>
      <%= image_tag url_for(current_student.avatar), class:"image-avatar", id: "avat" %>
    <% else %>
      <img src="<%= asset_path('avatar.jpg')%>" alt="avatar" id="avat" class="image-avatar">
    <% end %>
    <%= current_student.firstname %>
  </a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="collapsibleNavbar">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to "Dashboard", homes_path , :class => 'nav-link' %>
      </li>

      <li class="nav-item">
        <%= link_to "Laporanku", homes_myreports_path, :class => 'nav-link' %>
      </li>

      <li class="nav-item">
        <%= link_to "Profil", profile_index_path, :class => 'nav-link' %>
      </li>

      <li class="nav-item">
        <%= link_to "Logout", destroy_student_session_path, method: :delete, :class => 'nav-link logout', :id => "logout"   %>
      </li>
    </ul>
  </div>
</nav>

<div style="overflow-x:auto;">
  <table>
    <tr>
      <th>Tanggal</th>
      <th>Puasa</th>
      <th>Tadarus</th>
      <th>Tarawih</th>
      <th>Subuh</th>
      <th>Dzuhur</th>
      <th>Ashar</th>
      <th>Magrib</th>
      <th>Isya</th>
      <th>Duha</th>
      <th>Tahajud</th>
      <th>Taubat</th>
      <th>Hajat</th>
      <th>Alasan</th>
    </tr>
    <% @report_ramadhans.each do |report_ramadhan| %>
      <tr>
        <td><%= report_ramadhan.tanggal.to_date %></td>
        <td><%= report_ramadhan.puasa %></td>
        <td><%= report_ramadhan.tadarus %></td>
        <td><%= report_ramadhan.tarawih %></td>
        <td><%= report_ramadhan.subuh %></td>
        <td><%= report_ramadhan.dzuhur %></td>
        <td><%= report_ramadhan.ashar %></td>
        <td><%= report_ramadhan.magrib %></td>
        <td><%= report_ramadhan.isya %></td>
        <td><%= report_ramadhan.duha %></td>
        <td><%= report_ramadhan.tahajud %></td>
        <td><%= report_ramadhan.taubat %></td>
        <td><%= report_ramadhan.hajat %></td>
        <td><%= report_ramadhan.alasan %></td>
      </tr>
    <% end %>
  </table>
  <center>
    <%= paginate @report_ramadhans, theme: 'twitter-bootstrap-4' %>
  </center>
</div>

app/views/stages/_form.html.erb
<%= form_with(model: stage, local: true) do |form| %>
  <% if stage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stage.errors.count, "error") %> prohibited this stage from being saved:</h2>

      <ul>
        <% stage.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :grade %>
    <%= form.text_field :grade %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stages/edit.html.erb
<h1>Editing Stage</h1>

<%= render 'form', stage: @stage %>

<%= link_to 'Show', @stage %> |
<%= link_to 'Back', stages_path %>

app/views/stages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stages</h1>

<table>
  <thead>
    <tr>
      <th>Grade</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stages.each do |stage| %>
      <tr>
        <td><%= stage.grade %></td>
        <td><%= link_to 'Show', stage %></td>
        <td><%= link_to 'Edit', edit_stage_path(stage) %></td>
        <td><%= link_to 'Destroy', stage, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stage', new_stage_path %>

app/views/stages/new.html.erb
<h1>New Stage</h1>

<%= render 'form', stage: @stage %>

<%= link_to 'Back', stages_path %>

app/views/stages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Grade:</strong>
  <%= @stage.grade %>
</p>

<%= link_to 'Edit', edit_stage_path(@stage) %> |
<%= link_to 'Back', stages_path %>